"""
Flask app to serve the honeypot analytics dashboard.
Renders recent attempts + the charts generated by charts.py.
"""

from flask import Flask, render_template
import json

app = Flask(__name__)

LOG_FILE = "logs/attempts.jsonl"


def load_recent_events(limit=20):
    events = []

    try:
        with open(LOG_FILE, "r", encoding="utf-8") as file:
            for line in file:
                line = line.strip()

                if not line:
                    continue

                try:
                    event = json.loads(line)
                    events.append(event)
                except json.JSONDecodeError:
                    continue

    except FileNotFoundError:
        return []

    return events[-limit:][::-1]


@app.route("/")
def index():
    events = load_recent_events()

    charts = {
        "top_ips": "top_ips.png",
        "attempts_over_time": "attempts_over_time.png",
        "top_user_agents": "top_user_agents.png"
    }

    return render_template(
        "index.html",
        events=events,
        charts=charts
    )


if __name__ == "__main__":
    app.run(debug=True, port=5000)
